# SPDX-FileCopyrightText: Copyright © 2025 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Lei Xu <lei.xu@idiap.ch>
# SPDX-FileContributor: Pierre Beckmann <pierre.beckmann@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only

"""
HTML Composer - Combine fixed and LLM-generated HTML sections
"""

import json
from pathlib import Path
from html import escape


def create_base_html(title, subtitle):
    """Create the base HTML structure with header and styling"""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap" rel="stylesheet">
{_get_css_styles()}
</head>
<body>
<div class="container">
  <header>
    <div class="logo" aria-hidden="true"></div>
    <div>
      <h1>{escape(title)}</h1>
      <div class="subtitle">{subtitle}</div>
    </div>
  </header>
"""


def create_problem_section(problem_description):
    """Create the fixed problem description section"""
    return f"""
  <section class="grid">
    <div class="card" style="grid-column:span 12">
      <h2>Problem Description</h2>
      <details open>
        <summary>Show / hide</summary>
        <pre class="small">{escape(problem_description)}</pre>
      </details>
    </div>
  </section>
"""


def create_dag_section(plan_spec):
    """Create the fixed DAG visualization section"""
    agents = plan_spec.get('agents', [])
    edges = plan_spec.get('edges', [])

    if not agents:
        return ""

    agent_flow = " → ".join(agents)
    svg = _render_plan_svg(agents, edges)

    return f"""
  <section class="grid" style="margin-top:8px">
    <div class="card" style="grid-column:span 12">
      <h2>Execution Plan</h2>
      <p class="small">Adaptive router created this execution DAG:</p>
      <div class="meta" style="margin:12px 0">
        <span class="chip">{escape(agent_flow)}</span>
      </div>
      {svg}
    </div>
  </section>
"""


def generate_trace_visualization(llm, trace_data, problem_type, narrative_context="", style_hint="", extra_guidance=""):
    """
    Use LLM to generate problem-specific trace visualization HTML

    Args:
        llm: LLM generator instance
        trace_data: Dict with solver outputs, code, results, etc.
        problem_type: 'CSP', 'LP', 'FOL', 'SMT', etc.
        narrative_context: Guiding context for the LLM
        style_hint: Visual style preferences
        extra_guidance: Additional instructions

    Returns:
        HTML string (sections only)
    """
    from langchain.schema import HumanMessage

    # Load the trace visualization prompt
    prompt_path = Path(__file__).parent.parent / "prompt/prompts/helpers/trace_visualization.txt"

    if prompt_path.exists():
        with open(prompt_path, 'r') as f:
            prompt_template = f.read()
    else:
        # Fallback inline prompt
        prompt_template = """Generate HTML sections visualizing this solver trace.

Context: {context}
Narrative: {narrative_context}
Style: {style_hint}
Guidance: {extra_guidance}

Output HTML sections only (no full document)."""

    # Format the prompt
    context_str = json.dumps(trace_data, indent=2, ensure_ascii=False)

    full_prompt = prompt_template.format(
        context=context_str,
        narrative_context=narrative_context,
        style_hint=style_hint,
        extra_guidance=extra_guidance
    )

    # Call LLM
    messages = [HumanMessage(content=full_prompt)]
    response = llm(messages)

    html_content = response.content.strip()

    # Clean up markdown wrappers if present
    if html_content.startswith("```html"):
        html_content = html_content[7:]
    if html_content.startswith("```"):
        html_content = html_content[3:]
    if html_content.endswith("```"):
        html_content = html_content[:-3]

    return html_content.strip()


def compose_html(title, subtitle, problem_description, plan_spec, llm_generated_sections, output_file=None):
    """
    Compose complete HTML from fixed and LLM-generated parts

    Args:
        title: Page title
        subtitle: Subtitle with solver info
        problem_description: Problem text (fixed section)
        plan_spec: Dict with 'agents' and 'edges' for DAG
        llm_generated_sections: HTML sections generated by LLM
        output_file: Optional path to save HTML

    Returns:
        Complete HTML string
    """
    html_parts = []

    # Fixed parts
    html_parts.append(create_base_html(title, subtitle))
    html_parts.append(create_problem_section(problem_description))
    html_parts.append(create_dag_section(plan_spec))

    # LLM-generated parts
    html_parts.append(llm_generated_sections)

    # Footer and closing
    html_parts.append("""
  <footer>Generated on-demand visualization • Fixed sections + LLM-generated trace visualization</footer>
</div>
</body>
</html>
""")

    html = "\n".join(html_parts)

    if output_file:
        Path(output_file).write_text(html, encoding='utf-8')
        print(f"✓ HTML saved to: {output_file}")

    return html


def _render_plan_svg(agents, edges):
    """Render a simple horizontal DAG"""
    if not agents or len(agents) < 2:
        return ""

    count = len(agents)
    width = max(900, 200 * count)
    height = 150
    step = width / (count + 1)

    nodes_svg = []
    node_positions = {}

    colors = ["#7cc4ff", "#b892ff", "#4ade80", "#facc15", "#fb7185", "#38bdf8"]

    for idx, agent in enumerate(agents, start=1):
        x = step * idx
        y = height / 2
        node_positions[agent] = (x, y)
        fill = colors[(idx - 1) % len(colors)]

        nodes_svg.append(f"""
          <rect x="{x - 50}" y="{y - 25}" width="100" height="50" rx="10" fill="rgba(17,26,43,.95)" stroke="{fill}" stroke-width="2.5"/>
          <text x="{x}" y="{y + 5}" text-anchor="middle" font-size="12" fill="#e2e8f0" font-weight="600">{escape(agent)}</text>
        """)

    edges_svg = []
    for edge in edges:
        if '->' not in edge:
            continue
        source, target = edge.split('->', 1)
        source, target = source.strip(), target.strip()

        if source in node_positions and target in node_positions:
            x1, y1 = node_positions[source]
            x2, y2 = node_positions[target]
            edges_svg.append(f"""
              <line x1="{x1 + 50}" y1="{y1}" x2="{x2 - 50}" y2="{y2}" stroke="rgba(124,196,255,.8)" stroke-width="2" marker-end="url(#arrow)"/>
            """)

    return f"""
      <div class="svg-wrap" style="margin-top:12px">
        <svg viewBox="0 0 {width} {height}" width="100%" height="100%" role="img" aria-label="Execution DAG">
          <defs>
            <marker id="arrow" markerWidth="10" markerHeight="10" refX="7" refY="3" orient="auto">
              <path d="M0,0 L0,6 L9,3 z" fill="rgba(124,196,255,.9)"/>
            </marker>
          </defs>
          {"".join(edges_svg)}
          {"".join(nodes_svg)}
        </svg>
      </div>
    """


def _get_css_styles():
    """Return the CSS styles for the HTML"""
    return """
<style>
  :root{
    --bg:#0b1220;
    --panel:#111a2b;
    --soft:#1a2438;
    --ink:#e8eefc;
    --sub:#9fb3d9;
    --accent:#7cc4ff;
    --accent-2:#b892ff;
    --ok:#4ade80;
    --warn:#facc15;
    --bad:#fb7185;
    --cv:#8b5cf6;
    --nlp:#f59e0b;
    --sys:#10b981;
    --rl:#3b82f6;
    --theory:#ec4899;
    --code:#0f172a;
    --chip:#233251;
  }
  *{box-sizing:border-box}
  html,body{margin:0;padding:0;background:linear-gradient(180deg,#0b1220 0%, #0a0f1c 60%, #0b1220 100%);color:var(--ink);font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,"Helvetica Neue",Arial,"Noto Sans",sans-serif;line-height:1.55}
  a{color:var(--accent)}
  .container{max-width:1200px;margin:32px auto;padding:0 20px}
  header{display:flex;gap:16px;align-items:center;margin-bottom:24px}
  .logo{width:46px;height:46px;border-radius:12px;background:radial-gradient(120% 120% at 20% 20%, #7cc4ff 0%, #b892ff 40%, #111a2b 100%);box-shadow:0 10px 30px rgba(124,196,255,.25), inset 0 0 14px rgba(184,146,255,.3)}
  h1{font-size:30px;margin:0;font-weight:800;letter-spacing:.2px}
  .subtitle{color:var(--sub);margin-top:2px;font-weight:500}
  .grid{display:grid;gap:16px;grid-template-columns:repeat(12,1fr)}
  .card{grid-column:span 12;background:linear-gradient(180deg,var(--panel), #0f172a);border:1px solid rgba(124,196,255,.15);border-radius:16px;padding:18px 20px;box-shadow:0 10px 30px rgba(0,0,0,.25)}
  .card h2{margin:2px 0 10px 0;font-size:20px;letter-spacing:.2px}
  .card h3{margin:16px 0 8px 0;font-size:16px;color:#cbd5e1}
  .meta{display:flex;flex-wrap:wrap;gap:10px;margin-top:8px}
  .chip{background:var(--chip);color:var(--ink);padding:6px 12px;border-radius:999px;border:1px solid rgba(124,196,255,.18);font-size:12px;font-weight:600}
  code, pre{background:var(--code);color:#dbeafe;border-radius:10px}
  pre{padding:14px;overflow:auto;border:1px solid rgba(124,196,255,.18);font-size:12px;max-height:500px}
  table{width:100%;border-collapse:separate;border-spacing:0 6px}
  th,td{text-align:left;padding:8px 10px;font-size:13px}
  th{color:#cbd5e1;font-weight:700;border-bottom:1px solid rgba(124,196,255,.25)}
  tr{background:rgba(26,36,56,.65)}
  tr td:first-child{border-top-left-radius:10px;border-bottom-left-radius:10px}
  tr td:last-child{border-top-right-radius:10px;border-bottom-right-radius:10px}
  .mono{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace}
  .pill{display:inline-flex;align-items:center;gap:8px;padding:8px 10px;border-radius:999px;font-weight:700;font-size:14px}
  .pill.ok{background:rgba(34,197,94,.12);color:#bbf7d0;border:1px solid rgba(34,197,94,.35)}
  .pill.no{background:rgba(251,113,133,.12);color:#fecdd3;border:1px solid rgba(251,113,133,.35)}
  .pill.warn{background:rgba(250,204,21,.12);color:#fde68a;border:1px solid rgba(250,204,21,.35)}
  .callout{background:linear-gradient(180deg, rgba(124,196,255,.08), rgba(184,146,255,.08));border:1px dashed rgba(124,196,255,.35);padding:14px;border-radius:12px;margin-top:12px}
  .session-box{background:rgba(26,36,56,.8);border:1px solid rgba(124,196,255,.2);border-radius:12px;padding:14px;margin:8px 0}
  .session-box h4{margin:0 0 8px 0;font-size:15px;color:#cbd5e1;font-weight:700}
  .paper-badge{display:inline-block;padding:4px 8px;margin:3px;border-radius:6px;font-size:11px;font-weight:600;border:1px solid rgba(255,255,255,.12)}
  .paper-badge.cv{background:rgba(139,92,246,.2);color:#c4b5fd}
  .paper-badge.nlp{background:rgba(245,158,11,.2);color:#fcd34d}
  .paper-badge.sys{background:rgba(16,185,129,.2);color:#6ee7b7}
  .paper-badge.rl{background:rgba(59,130,246,.2);color:#93c5fd}
  .paper-badge.theory{background:rgba(236,72,153,.2);color:#f9a8d4}
  .oral-badge{background:rgba(124,196,255,.15);color:#7cc4ff;padding:3px 8px;border-radius:999px;font-size:11px;font-weight:600;margin-left:8px}
  .poster-badge{background:rgba(184,146,255,.15);color:#b892ff;padding:3px 8px;border-radius:999px;font-size:11px;font-weight:600;margin-left:8px}
  .svg-wrap{background:linear-gradient(180deg, rgba(59,130,246,.08), rgba(167,139,250,.08));border:1px solid rgba(124,196,255,.2);border-radius:16px;padding:16px}
  .small{font-size:13px;color:#c7d2fe}
  details{margin-top:8px}
  summary{cursor:pointer;font-weight:600;color:var(--accent);font-size:14px}
  footer{margin:30px 0 12px 0;color:#8aa2c8;font-size:12px;text-align:center}
  @media (max-width: 900px){ .grid{grid-template-columns:1fr} }
</style>
"""


__all__ = [
    "create_base_html",
    "create_problem_section",
    "create_dag_section",
    "generate_trace_visualization",
    "compose_html",
]
